# Generated by Django 4.2.2 on 2023-06-17 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponetName",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("displayName", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CRUDModel",
            fields=[
                ("seq_num", models.AutoField(primary_key=True, serialize=False)),
                ("operations", models.CharField(max_length=50, unique=True)),
                ("value", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["operations"],
            },
        ),
        migrations.CreateModel(
            name="UserRoleModel",
            fields=[
                ("seq_num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now_add=True)),
                ("views", models.JSONField(blank=True, null=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "createdBy"],
            },
        ),
    ]
