# Generated by Django 4.2.2 on 2023-06-17 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeederModel",
            fields=[
                ("seq_num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                (
                    "assignedTo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignedTo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "createdBy"],
            },
        ),
        migrations.CreateModel(
            name="StationModel",
            fields=[
                ("seq_num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                (
                    "assignedTo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "createdBy"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleModel",
            fields=[
                ("seq_num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("dateOn", models.DateField()),
                ("timeFrom", models.CharField(default="", max_length=16)),
                ("timeTo", models.CharField(default="", max_length=16)),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                ("pic_url", models.CharField(max_length=5000)),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "createdBy"],
            },
        ),
        migrations.CreateModel(
            name="FeederStationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feederId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emapp.feedermodel",
                    ),
                ),
                (
                    "stationId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emapp.stationmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["stationId"],
            },
        ),
        migrations.AddField(
            model_name="feedermodel",
            name="stationId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emapp.stationmodel",
            ),
        ),
    ]
