# Generated by Django 4.2.2 on 2023-06-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0002_feedermodel_stationmodel_schedulemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolemodel',
            name='feeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder', to='emapp.crudmodel'),
        ),
        migrations.AddField(
            model_name='userrolemodel',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='emapp.crudmodel'),
        ),
        migrations.AddField(
            model_name='userrolemodel',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station', to='emapp.crudmodel'),
        ),
    ]
