# Generated by Django 4.2.2 on 2023-06-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0003_userrolemodel_feeder_userrolemodel_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolemodel',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='emapp.crudmodel'),
        ),
    ]
