# Generated by Django 4.2.2 on 2023-06-19 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0004_userrolemodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolemodel',
            name='urjauser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urjauser', to='emapp.crudmodel'),
        ),
    ]
