# Generated by Django 4.2.2 on 2023-06-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0005_userrolemodel_urjauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemodel',
            name='feederId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emapp.feedermodel'),
        ),
    ]
