# Generated by Django 4.2.2 on 2023-06-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0006_schedulemodel_feederid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedermodel',
            name='assignedTo',
        ),
        migrations.RemoveField(
            model_name='stationmodel',
            name='assignedTo',
        ),
        migrations.AddField(
            model_name='feedermodel',
            name='feederCode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='feedermodel',
            name='feederManager',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='stationCode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='stationManager',
            field=models.CharField(default='', max_length=50),
        ),
    ]
