# Generated by Django 4.2.2 on 2023-06-20 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emapp', '0007_userrolemodel_control_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemodel',
            name='status',
            field=models.CharField(default='Scheduled', max_length=50),
        ),
        migrations.CreateModel(
            name='UserFeeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emapp.feedermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
