# Generated by Django 4.2.2 on 2023-06-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0007_remove_feedermodel_assignedto_and_more'),
        ('emapp', '0009_rename_feeder_userfeeder_feederid_and_more'),
    ]

    operations = [
    ]
