# Generated by Django 4.2.2 on 2023-07-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0010_merge_20230624_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedermodel',
            name='contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
    ]
